### ISSUE TITLE
Documentation: How do I log to a file? 

### ISSUE THREAD

**Issue by vamshiaruru-virgodesigns** [starlite-api/starlite#1083]
Hi all, apologies if this is answered else where in the documentation or if it is obvious. But, how do I configure starlite logging to log to a file instead of console? I would like to be able to make the logging middleware to log to the file as well.

Moreover, how do I use the logger configured by starlite outside of the request function? In fastapi I used to configure the logger manually and do 
```python
import logging
logger = logging.getLogger(__name__)
```
and be done with it.  What do I do in starlite? Are there any examples I can refer to? TIA!

**Comment by provinzkraut** [comment]
> Moreover, how do I use the logger configured by starlite outside of the request function?

You can access the `"starilte"` logger just like you would any other logger:

```python
import logging

logger = logging.getLogger("starlite")
```

but you should really use a separate logger for your application, instead of Starlite's own. 

> But, how do I configure starlite logging to log to a file instead of console?

Same as above: You can configure the Starlite logger the same as you would any other logger. It uses the standard logging configuration, so you can pass in everything you would to `logging.config.dictConfig`. I recommend you check out the documentation on that: https://docs.python.org/3/library/logging.config.html#logging.config.dictConfig.

Here's an example on how you could setup a `FileHandler`:

```python
from starlite import LoggingConfig, Starlite

app = Starlite(
    route_handlers=[],
    logging_config=LoggingConfig(
        handlers={
            "file_handler": {
                "class": "logging.FileHandler",
                "filename": "starlite.log",
            }
        },
        loggers={
            "starlite": {
                "level": "INFO",
                "handlers": ["file_handler"],
            }
        },
    ),
)
```

This is not explicitly described in the documentation, since logging configuration is a rather complex topic, not something special to Starlite, and the standard library documentation is fairly exhaustive:

- [Basic logging tutorial](https://docs.python.org/3/howto/logging.html#logging-basic-tutorial)
- [Advanced logging tutorial](https://docs.python.org/3/howto/logging.html#logging-advanced-tutorial)
- [Logging cookbook](https://docs.python.org/3/howto/logging-cookbook.html#logging-cookbook)

**Comment by vamshiaruru-virgodesigns** [comment]
Thank you so much for the help @provinzkraut , I have tried exactly what you've said. It still logs to console :) Here's my code
```python
from typing import Dict

from starlite import (
    CompressionConfig,
    CORSConfig,
    LoggingConfig,
    Request,
    Starlite,
    get,
)
from starlite.middleware import LoggingMiddlewareConfig

@get("/")
async def hello_world() -> Dict[str, str]:
    return {"hello": "world"}


@get("/health/")
async def health_check(request: Request) -> Dict[str, str]:
    request.logger.info("This is health")
    return {
        "service": "Ok",
        "db": "Ok",
    }


cors_config = CORSConfig(
    allow_credentials=True,
)
compression_config = CompressionConfig(minimum_size=100, backend="gzip")
logging_middleware_config = LoggingMiddlewareConfig()

app = Starlite(
    route_handlers=[hello_world, health_check],
    cors_config=cors_config,
    compression_config=compression_config,
    logging_config=LoggingConfig(
        handlers={
            "file_handler": {
                "class": "logging.FileHandler",
                "filename": "starlite.log",
            }
        },
        loggers={
            "starlite": {
                "level": "INFO",
                "handlers": ["file_handler"],
            }
        },
    ),
    middleware=[logging_middleware_config.middleware],
)
```
I'm not sure what I am doing wrong.

**Comment by provinzkraut** [comment]
Seems to work fine for me. Is it not logging to `starlite.log` for you or does it simply also log to the console?

**Comment by vamshiaruru-virgodesigns** [comment]
So, the middleware that logs access logs is logging to the file, but `request.logger` is logging only to console.

**Comment by Goldziher** [comment]
Have you defined a logger for your app? 

If you access request.app.get_logger(__name__) what's the result?

**Comment by Goldziher** [comment]
closing this - unless you need further assitance.
