### ISSUE TITLE
Enhance multipart handling

### ISSUE THREAD

**Issue by Goldziher** [starlite-api/starlite#12]
Starlite currently uses the Starlette built-in multipart handling, which is somewhat limited. @adriangb has proposed to enhance this by supporting different encodings and data.

**Comment by adriangb** [comment]
Linking #8 since it is related.

Starlette _does_ support receiving forms with different encodings in the parts. It's just that it gives you everything as an UploadFile or a string. So this framework would have to build on top of that and e.g. parse the string into JSON -> into a Pydantic model, or parse the string into a Form, etc.

**Comment by Goldziher** [comment]
Why not implement this? What are the cons?

**Comment by Goldziher** [comment]
@adriangb - so, whats the status of this? do you intend to add a PR addressing this? 

As far as I am concerned it shouldn't be a problem to resolve this using typing data. Namely, the data should be parsed into python based on the encoding, and then transformed into the data type set by the user.

**Comment by adriangb** [comment]
There were some parts of this that were not clear to me w.r.t the syntax, how deeply you want to support this, etc. It seems like you're moving pretty fast and already implemented something in #23, so I'll go ahead and close this issue. Thanks!
