### ISSUE TITLE
Skip middleware for certain handlers/routers/paths

### ISSUE THREAD

**Issue by Bobronium** [starlite-api/starlite#169]
Is there a preferred way of enabling a middleware only for a specific set of handlers?

Say, I want `secret` handler to require auth and `health_check` to be accessible without one:
```py
from starlite import Request, get

from my_app.security.auth import Token, User


@get(path="/secret")
async def secret(request: Request[User, Token]) -> str:
    """Should require auth"""
    return user.username


@get(path="/")
def health_check() -> str:
    """Should not require auth"""
    return "healthy"
```

One way I found is checking for path inside the middleware and return `AuthenticationResult(user=None, auth=None)` if auth is not required, but I find it a bit quirky.

Ideally, I'd do something like this:

```py
...

@get(path="/secret")
@authenticate
async def secret(request: Request[User, Token]) -> str: ...

@get(path="/")
def health_check() -> str: ...
```

or, perhaps

```py
...

regular_router = Router(path="/", route_handlers=[health_check])
auth_router = Router(path="/", route_handlers=[secret], middleware=[AuthMiddleware])
```

**Comment by peterschutt** [comment]
Can you please show the example of the working solution that you found by checking path in the middleware?

**Comment by peterschutt** [comment]
Thanks for opening the issue, I think this is a problem that we need to solve. It would be very common for services to have a mix of authn and open routes.

IMO, having an `allow-list` of routes defined in a single location that can bypass authn could be perceived as beneficial, compared to having that logic dispersed throughout the code base. 

If we were to go the decorator route, I think i'd prefer `@skip_auth` or something like that, so it was explicitly opt out, rather than in. Also, it would probably be better to have `@get(..., skip_auth=True)`, i.e., extend the existing route decorators.

So if you can provide that example of the middleware with path inspection built in, I think we should discuss that first as as we could include an example in the docs of the pattern without having to modify any Starlite code, just as a first step.

Then, we can consider if/how we should modify Starlite to make the experience for something like this nicer.

**Comment by mybigman** [comment]
> If we were to go the decorator route, I think i'd prefer `@skip_auth` or something like that, so it was explicitly opt out, rather than in. Also, it would probably be better to have `@get(..., skip_auth=True)`, i.e., extend the existing route decorators.

I am not sure this approach is right either since your only thinking about a single middleware.

What if I want 3 middlewares on a certain controller or single endpoint.

@Bobronium approach is good start on the `Router`, however it would be good to apply to a single route, group of routes or globally.

I use `laravel framework` quite heavily for work and that approach works quite well. You can read more about its [middleware](https://laravel.com/docs/9.x/middleware#main-content).

I've keen to build something in a python framework using either `starlite` or `fastapi` just to see how it compares and get back into python since I am so rusty.

**Comment by peterschutt** [comment]
> What if I want 3 middlewares on a certain controller or single endpoint.

Three layers of authentication middleware?

**Comment by mybigman** [comment]
Sorry, thought whilst we looking at it be a good idea to look at the bigger picture :)

**Comment by peterschutt** [comment]
Absolutely no problem, and it is a discussion worth having.

At the moment we resolve the middleware stack on app initialization time and the whole stack is run before the route handler is resolved. But perhaps the middlewares could be resolved per handler like we resolve out all the other configs, we resolve the handler first and then get the middleware stack from it, execute the stack and finally call the handler. 

There would have to be a bit of a reorganization of the way the inbound requests are handled to accommodate it, and I don't know what I don't know about it either, so there's a good chance there's some complication I'm missing. I might have a play around with a POC.

**Comment by Goldziher** [comment]
My thinking as well. I think this is the way to go - allow middleware definitions per route handler, controller, router or app. 

We need to consider some things in general - 

1. The more middlewares are added, the slower request processing is, because this is in effect a bunch of chained async calls. We thus need to resolve this stack in an optimal way per route handler and cache the resolved stack. 

2.  Not necessarily in the same scope, but still pertinent maybe: We should consider how to add data regarding middlewares to the OpenAPI docs. An example would be adding an authentication entry for some routes based on middlewares.

**Comment by Bobronium** [comment]
> Can you please show the example of the working solution that you found by checking path in the middleware?


```py
from dataclasses import dataclass
from starlette.requests import HTTPConnection

from starlite import AbstractAuthenticationMiddleware, AuthenticationResult, NotAuthorizedException

from myapp.security.jwt import decode_jwt_token

API_KEY_HEADER = "X-API-KEY"


@dataclass
class User:
    id: int
    username: str


USERS = {
    1: User(1, 'bob'),
    2: User(2, 'bab'),
}

class JWTAuthenticationMiddleware(AbstractAuthenticationMiddleware):
    async def authenticate_request(self, request: HTTPConnection) -> AuthenticationResult:
        """
        Given a request, parse the request api key stored in the header and retrieve the user correlating to the token
        """
        if request.base_url.path in {"/"}:
            return AuthenticationResult(user=None, auth=None)

        # retrieve the auth header
        auth_header = request.headers.get(API_KEY_HEADER)
        if not auth_header:
            raise NotAuthorizedException()
        
        token = decode_jwt_token(encoded_token=auth_header)
        
        user = USERS.get(token.uid)
        if not user:
            raise NotAuthorizedException()

        return AuthenticationResult(user=user, auth=token)

```


While we're here, I think auth middleware example in the docs is incomplete, since it doesn't consider how user would get the token. 

One way is having a handler that doesn't require auth, but expects other type of credentials in the body, hence this issue :)

**Comment by peterschutt** [comment]
> I think auth middleware example in the docs is incomplete

Docs contributions are gratefully accepted:)

**Comment by Goldziher** [comment]
I added a draft PR here -> https://github.com/starlite-api/starlite/pull/173, please checkout the code and add comments (see the description).
