### ISSUE TITLE
Documentation: Inherited members

### ISSUE THREAD

**Issue by peterschutt** [starlite-api/starlite#427]
We extend `Starlette` types for many of our public api types, e.g., `Request`. This task is to work out the best way to have members of those super classes show in our reference docs.

Mkdocstrings has an `inherited_members` config, but at this point [it doesn't work](https://github.com/mkdocstrings/mkdocstrings/issues/459).

This is compounded by the fact that `starlette` doesn't have reference docs themselves, so no `objects.inv` to import to allow us to cross-ref to their docs for the types we extend.

**Comment by peterschutt** [comment]
https://github.com/mitmproxy/pdoc is an alternative for generating ref docs. Found this similar issue: https://github.com/mitmproxy/pdoc/issues/295 which has a solution.

**Comment by provinzkraut** [comment]
How does that integrate with mkdocs?

**Comment by peterschutt** [comment]
> How does that integrate with mkdocs?

Found this: https://github.com/mitmproxy/pdoc/tree/main/examples/mkdocs

This isn't something we'd want to rush into probably, but if we get to the point that we think it is worth it, we can either do the work upstream to make this work in mkdocstrings, or know that there is at least one alternative.

**Comment by provinzkraut** [comment]
Hmmm.. At that point we might as well be using sphinx with a material theme and markdown extension :D

I'll fiddle with some of the solutions at some point during the near future.

**Comment by jtraub** [comment]
> Hmmm.. At that point we might as well be using sphinx with a material theme and markdown extension :D

mkdocs is so much better. I would rather try to stick to it.

**Comment by provinzkraut** [comment]
That's very subjective I think. Personally I much prefer Sphinx, since for more complex things (which technical documentation of a project like this) it's just better suited. Alone the way interfaces are documented is much more legible in Sphinx, and it's way more mature and stable than Mkdocs (and mkdocstrings in particular), let alone the fact that reST comes with most of the stuff built in and a more concise syntax than the host of markdown extensions needed to make it work for technical writing (which makes sense, since reST was built specifically for this purpose, and markdown was never intended to do such things).

I admit that I haven't worked on larger mkdocs projects before starlite, but I've read quite a few of them by now and especially the whole material design aspect just doesn't seem very suited to me for a technical document. It may be nice for end-user website (although that's also a matter of taste), but looking nice isn't really the main objective for documentation. 

Personally, I believe that the rise in mkdocs popularity in the Python ecosystem is mainly due to the admittedly very steep learning curve of Sphinx. I'd also love to see some of the nice features that mkdocs has going for it added to sphinx.

Anyway, this isn't really up for debate here I think since our current docs are the way they are and I don't see a complete rewrite for Sphinx happen any time soon.

**Comment by jtraub** [comment]
> but looking nice isn't really the main objective for documentation

I don't care about the look. Snappy (almost instant) search is what makes me strongly prefer Material for MkDocs.

**Comment by Goldziher** [comment]
I do care about the look... We need to be accessible, not only to the hardcore technical people or the old school devs who think reading man files in their vi editor is the thing.

**Comment by provinzkraut** [comment]
> I do care about the look... We need to be accessible, not only to the hardcore technical people or the old school devs who think reading man files in their vi editor is the thing.

Well, Sphinx has nice themes too. Material ones even. But as I said, I don't think moving at this point is feasible, so there's no point discussing this here 🙃 

>As for cross referencing to other libs. What libraries do we need here aside from multidict?

Afaik only multidict and the stdlib. We might want to refrence `fsspec` too, I think that shouldn't be a problem though.

I wanted to look into the mkdocstrings-inheritance issue during my docs overhaul and see if I can't help fix things upstream.
