### ISSUE TITLE
Enhancement: API Rate Throttling

### ISSUE THREAD

**Issue by cofin** [starlite-api/starlite#470]
**What's the feature you'd like to ask for.**
Implement an API throttling mechanism for routes.

**Additional context**

**Comment by sondrelg** [comment]
The [starlette docs](https://www.starlette.io/middleware/#ratelimitmiddleware) point at [asgi-ratelimit](https://github.com/abersheeran/asgi-ratelimit) for this. Isn't that sufficient?

**Comment by Goldziher** [comment]
> The [starlette docs](https://www.starlette.io/middleware/#ratelimitmiddleware) point at [asgi-ratelimit](https://github.com/abersheeran/asgi-ratelimit) for this. Isn't that sufficient?

We already have support for cache backend. So we can actually implement this in house. Would probably be better.

**Comment by Goldziher** [comment]
So I'd like to discuss how to implement this. 

The first example I know well is the system implemented by [Django Rest Framework](https://www.django-rest-framework.org/api-guide/throttling/), which uses "throttling classes".  

1. My thinking is to allow for Callables (functions, methods or classes that implement `__call__`) that receives the request object and the route handler class (similarly to `Guard` functions), and returns a boolean whether the request should be allowed to proceed or not. I.e. the signature will be `Callable[[Request, HTTPRouteHandler], SyncOrAsyncUnion[bool]]`. Like guards it will receive the route handler object and be able to access the `opt` value set on the handler, if any. 

2. We could also add a base class `AbstractThrottle`, that will have baked in `exclude` functionality like the `AbstractAuthenticationMiddleware` has. I don't think that we should force users to use classes, or our abstract middleware as a basis, but that this can be a nice addition.

3. Our cache backend should be more thread safe than Django's because of the implementation we have these with async locks. But we should certainly include a warning like DRF has regarding throttling not being a security mechanism and about precision not being guaranteed where concurrency is concerned.

**Comment by Goldziher** [comment]
I started with a class based structure - I followed DRF as an example here. I dont think we can really use a functional approach here, because its a bit more complex. Please see the draft PR and comment.
