### ISSUE TITLE
Enhancment: Replace starlette's `CORSMiddleware` with our own implementation

### ISSUE THREAD

**Issue by provinzkraut** [starlite-api/starlite#669]
This is part of #612. Some details have already been laid out there.

**Comment by seladb** [comment]
I think I can take it

**Comment by Goldziher** [comment]
@seladb wassup? any progress?

**Comment by seladb** [comment]
Hi @Goldziher! I'm currently busy creating a new release for [PcapPlusPlus](https://github.com/seladb/PcapPlusPlus) (my other open-source project) so I don't have much time to contribute to Starlite. Then I'm planning to take some time off. If someone wants to take this issue please feel free to do so. Otherwise, I hope I'll be able to get back to it by the end of November

**Comment by Goldziher** [comment]
hi, ok thanks. No I would like to get this done within the next week or so. So I will take this over.
