### ISSUE TITLE
Custom Middleware with a kwarg fails to load

### ISSUE THREAD

**Issue by ThinksFast** [starlite-api/starlite#689]
**Describe the bug**
I am trying to use `APScheduler` with Starlite.  [APScheduler](https://github.com/agronholm/apscheduler) is a background task scheduling package.  I am currently using their latest alpha version `4.0.0a2`.  They have [a working example for Starlette](https://github.com/agronholm/apscheduler/blob/4.0.0a2/examples/web/asgi_starlette.py) (copied below), but when I adapt the code for Starlite (below), it seems the middleware is never called.  

When I try to debug, I can see the `SchedulerMiddleware` gets initialized, but the `__call__` dunder doesn't seem to get called, I never get to step through the code.

Based on the [Starlite middleware docs](https://starlite-api.github.io/starlite/usage/7-middleware/2-creating-middleware/2-using-middleware-protocol/), I believe I'm calling this middleware correctly [with the kwarg](https://starlite-api.github.io/starlite/usage/7-middleware/1-using-middleware/3-define-middleware/).  

Have I don't something wrong, or is this a bug?

**To Reproduce**
The code below should run as-is.   Only requirements are `Starlite=1.32.0`, `Uvicorn` and `APScheduler=4.0.0a2`. 

Expected result:  print or log statement every second from the `tick()` function.  Actual result is nothing.

```
from __future__ import annotations

import logging
from datetime import datetime

import uvicorn
from apscheduler.datastores.async_sqlalchemy import AsyncSQLAlchemyDataStore
from apscheduler.eventbrokers.asyncpg import AsyncpgEventBroker
from apscheduler.schedulers.async_ import AsyncScheduler
from apscheduler.triggers.interval import IntervalTrigger
from sqlalchemy.ext.asyncio import create_async_engine
from starlite import DefineMiddleware, Request, Starlite, State, get
from starlite.middleware.base import MiddlewareProtocol
from starlite.types import ASGIApp, Receive, Scope, Send

logger = logging.getLogger(__name__)


def tick():
    print("Hello, the time is", datetime.now())
    logger.info("Hello, the time is", datetime.now())


class SchedulerMiddleware(MiddlewareProtocol):
    def __init__(
        self,
        app: ASGIApp,
        scheduler: AsyncScheduler,
    ) -> None:
        super().__init__(app)
        self.app = app
        self.scheduler = scheduler

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        if scope["type"] == "lifespan":
            async with self.scheduler:
                await self.scheduler.add_schedule(
                    tick, IntervalTrigger(seconds=1), id="tick"
                )
                await self.scheduler.start_in_background()
                await self.app(scope, receive, send)
        else:
            await self.app(scope, receive, send)


@get("/")
async def root(request: Request, state: State) -> str:
    return "Hello, world!"


engine = create_async_engine("postgresql+asyncpg://postgres:secret@localhost/testdb")
data_store = AsyncSQLAlchemyDataStore(engine)
event_broker = AsyncpgEventBroker.from_async_sqla_engine(engine)
scheduler = AsyncScheduler()
middleware = [DefineMiddleware(SchedulerMiddleware, scheduler=scheduler)]

app = Starlite(route_handlers=[root], middleware=middleware)

if __name__ == "__main__":
    uvicorn.run(app, host="127.0.0.1", port=8000)

```

**Additional context**
Here is an example using Starlette which works:

```
from __future__ import annotations

from datetime import datetime

from apscheduler.datastores.async_sqlalchemy import AsyncSQLAlchemyDataStore
from apscheduler.eventbrokers.asyncpg import AsyncpgEventBroker
from apscheduler.schedulers.async_ import AsyncScheduler
from apscheduler.triggers.interval import IntervalTrigger
from sqlalchemy.ext.asyncio import create_async_engine
from starlette.applications import Starlette
from starlette.middleware import Middleware
from starlette.requests import Request
from starlette.responses import PlainTextResponse, Response
from starlette.routing import Route
from starlette.types import ASGIApp, Receive, Scope, Send


def tick():
    print("Hello, the time is", datetime.now())


class SchedulerMiddleware:
    def __init__(
        self,
        app: ASGIApp,
        scheduler: AsyncScheduler,
    ) -> None:
        self.app = app
        self.scheduler = scheduler

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        if scope["type"] == "lifespan":
            async with self.scheduler:
                await self.scheduler.add_schedule(
                    tick, IntervalTrigger(seconds=1), id="tick"
                )
                await self.scheduler.start_in_background()
                await self.app(scope, receive, send)
        else:
            await self.app(scope, receive, send)


async def root(request: Request) -> Response:
    return PlainTextResponse("Hello, world!")


engine = create_async_engine("postgresql+asyncpg://postgres:secret@localhost/testdb")
data_store = AsyncSQLAlchemyDataStore(engine)
event_broker = AsyncpgEventBroker.from_async_sqla_engine(engine)
scheduler = AsyncScheduler()
routes = [Route("/", root)]
middleware = [Middleware(SchedulerMiddleware, scheduler=scheduler)]
app = Starlette(routes=routes, middleware=middleware)

```

**Comment by Goldziher** [comment]
We currently don't give Middleware access to the asgi LifeSpan events. That's what's going on there. Scaffolding the scheduler should happen in `on_startup`.

**Comment by provinzkraut** [comment]
> `on_startup=[anyio.sleep_forever]`

That's because this will, well, sleep forever. The suggestion was to run the scaffolding within `on_startup`, not the whole thing.

If you provide some code we might be able to help you further.

**Comment by provinzkraut** [comment]
Okay so the issue here is that the scheduler itself acts as a task group [you can see this here](https://github.com/agronholm/apscheduler/blob/05e15f073aeb74bbbf2e37379df5fe15c9867d30/src/apscheduler/schedulers/async_.py#L114), to emulate a "background task", but it does not actually run in the background. Instead, when exiting the context manager, it will wait for all tasks to finish, which in this case never happens. 

The implementation of this library is simply a bit at odd with Litestar's lifespan architecture. I don't think there's an easy way to solve this without adding hacky workarounds for the hacky workarounds of this library.

You *could* use `asyncio.create_task` to run these things, which is exactly what this library tries to prevent by operating the way it does.

@litestar-org/maintainers we might want to consider adding a canonical way to do this. AnyIO refuses to add native functionality for things like this, but the implementation of libraries like appscheduler clearly show there's a need, and we currently also have two things (event emitter and the yet-to-merge #1587) which are currently implemented using tasks, which could benefit from this.

**Comment by provinzkraut** [comment]
> So, Simply speaking, Litestar can't work with a a pure `ASGI` middleware ?

It can. That's exactly what my example does. 

I think this may be an issue of terminology. 

"ASGI middleware" isn't really thing. It's just a commonly used term to describe a certain pattern, but in reality, it's all just ASGI applications, that is, a callable that accepts `scope`, `send` and `receive`. Litestar, being an ASGI application, supports that of course. This also means you can simply wrap your Litestar app in another app, which is what I do in my example.

The middlewares provided by libraries like Starlette and Litestar are simply helpers to make developing and using this pattern a bit more convenient.

> But, Your solution looks like a hack to me

It is in fact not. This is exactly how all ASGI middlewares are implemented, since this is how the protocol was designed. Nothing there is Litestar specific.
