### ISSUE TITLE
Enhancement: OIDC Security Backend

### ISSUE THREAD

**Issue by Goldziher** [starlite-api/starlite#878]
As we discussed in #794 - we would like to have an OIDC integration as an optional component in `starlite.contrib.oidc`. This will have to rely on `pyoidc`, which while problematic is the only fully fledged OIDC implementation in python and also has a usable license. 

Our implementation should support all the flows supported by `pyoidc` with an easy to use abstraction layer. For reference: https://darutk.medium.com/diagrams-of-all-the-openid-connect-flows-6968e3990660

**Comment by Goldziher** [comment]
So, after looking into `pyoidc` I am dubious we should actually integrate this inside Starlite. This library is too messy and is going to be hard to maintain - this should be done in an external library, outside of our github org,  probably by someone else who is willing to maintain this. 

Open to people who want to pick this up - this issue though is going to be closed here. 

fyi @infohash if you want to publish you own lib.

**Comment by v3ss0n** [comment]
any OIDC supportin coming in 2.0 ? the starlite-oidc is also abandoned right?

**Comment by infohash** [comment]
While there is no planned date for OIDC extension of starlite 2.0, I have prepared a requirement to create an OIDC extension which will wrap [idpy-oidc](https://github.com/IdentityPython/idpy-oidc), the latest OpenID foundation certified OIDC lib in Python with latest OIDC features and addons.

The problem I am facing is even though **idpy-oidc** is the latest revision of OIDC implementation for Python, its design pattern still does not look modern and it is not async so a wrapper around it for starlite cannot be maintained by starlite-api. I have 2 options:

1. Either I port **idpy-oidc** lib to an async version and then write a starlite extension on top of it.
2. Or Just use the lib as is and write a wrapper around it.

Both have its own problems and complexity with maintainability of code (and security if I port **idpy-oidc** to an async version).

The reason I no longer want to use **pyoidc** lib as base is because it's not async, it has legacy design pattern and it does not have all the features of OIDC like the most popular one is OIDC-PKCE (**idpy-oidc** has this one though).

**Comment by v3ss0n** [comment]
also this one , looks maintained : https://github.com/kroketio/quart-keycloak could this be adapted?

**Comment by infohash** [comment]
`psion` only has OIDC Authorization Code Flow without its addons like PKCE, PAR, etc and [`quart-keycloak`](https://github.com/kroketio/quart-keycloak) only supports Keycloak as an **adapter** and not as a generic client. See the complete list of features that `idpy-oidc` supports which will soon also support OIDC CIBA so its great that Roland Hedberg has taken care of everything including the crypto but being async is kind of a cool thing to have specially for the async frameworks.

I think FastAPI does have a custom third party OIDC extension and there is also a well maintained and fully compliant **authlib** for Python but with BSD license for open source projects and a commercial license for industrial projects. The problem with writing a security lib like this is if it is not certified or at least not fully compliant with the OIDC spec, its adoption rate in the industrial projects will be very slow.

**Comment by v3ss0n** [comment]
Have you checked oauthlib ?

**Comment by infohash** [comment]
oauthlib is a legacy version of authlib.

**Comment by v3ss0n** [comment]
how about https://github.com/frankie567/httpx-oauth ?

**Comment by v3ss0n** [comment]
@infohash  https://github.com/lepture/authlib/issues/475 the author saids that allows to use BSD License on Closed Source Projects  (can choose any) .

**Comment by mcclade** [comment]
For corporates any license condition that requires a conversation is going to block usage.

“Why is starlite being blocked by the package manager?” 

“Oh, one of its dependencies is on a dual license. You need to speak to Steve in Legal to explain what you’re using it for and get agreement that your use case matches this guy’s vague statement on a GitHub issue”

“Yeah… I’ll just use something else.”

**Comment by infohash** [comment]
@v3ss0n httpx-oauth has partial implementation of OIDC. As for authlib, what @mcclade said. It will deter industrial projects to use such an extension that wraps a dual licensed code.

**Comment by v3ss0n** [comment]
Its seems that BlackSheep's OIDC looks like the best fit for starlite as @Goldziher  suggested .
I am free a few weeks , and we are going to rebuild our project management platform - which would need OIDC . 
We are going to opensource our work on OIDC too.
