### ISSUE TITLE
Bug: Jinja Template response ignores MediaType settings

### ISSUE THREAD

**Issue by ThinksFast** [starlite-api/starlite#964]
**Describe the bug**
Jinja template responses always return `content-type: text/html`, even when `media_type` is set to another value.  

**To Reproduce**
In this example handler, I am trying to return a plain text response.  But the actual result is `text/html`

```python
class FrontEnd(Controller):
    @get("/robots.txt")
    async def serveRobots(self, request: Request, state: State) -> Template:
        return Template(name="robots.txt.j2", media_type=MediaType.TEXT)
```

Setting the `media_type` on the route decorator doesn’t work either:

`@get("/robots.txt", media_type=MediaType.TEXT)`

**Additional context**
I’m on my phone at the moment, but happy to provide an MRCE if needed.

**Comment by provinzkraut** [comment]
To reproduce: 

```python
from starlite import MediaType, Template, TemplateConfig, create_test_client, get
from starlite.contrib.jinja import JinjaTemplateEngine


@get("/", media_type=MediaType.TEXT)
async def serveRobots() -> Template:
    return Template(name="robots.txt")


with create_test_client(
    [serveRobots],
    template_config=TemplateConfig(engine=JinjaTemplateEngine(directory="templates")),
) as client:
    assert client.get("/").headers["content-type"].startswith("text/text")
```

**Comment by provinzkraut** [comment]
Okay so there's a bit of an issue with this. 
Currently we force the media type to HTML, because the media type we receive will always be `application/json` by default. Since this default is passed down to `Template`, in `Template` there's no way of knowing if this was the default or deliberately set. 

A workaround would be to check if the media type is `application/json`, assuming that's the default, and setting the media type to `text/html` if it is.

The proper way to handle this would be to defer media type setting to a later point / enable default media types for response, but I'm not sure how / if this interferes with OpenAPI generation.

@Goldziher WDYT?
